name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install libomp (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install libomp
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Configure Windows PATH
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        echo "$HOME\.poetry\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$env:APPDATA\Python\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "$env:LOCALAPPDATA\Programs\Python\Python313\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    
    - name: Install dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          # On Windows, find where poetry is installed
          which poetry || echo "Poetry not found in PATH"
          export PATH="$HOME/.poetry/bin:$APPDATA/Python/Scripts:$PATH"
          python -m poetry --version
          python -m poetry install --with dev
        else
          poetry --version
          poetry install --with dev
        fi
    
    - name: List test files
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          cmd /c "dir tests /s"
        else
          ls -R tests
        fi
    
    - name: Run tests
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          export PATH="$HOME/.poetry/bin:$PATH"
          python -m poetry run pytest tests -s -x --cov=bitser -vv
        else
          poetry run pytest tests -s -x --cov=bitser -vv
        fi
      
    - name: Upload coverage
      uses: codecov/codecov-action@v4
