name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install libomp (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install libomp
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: poetry install --with dev
    
    - name: List test files
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          cmd /c "dir tests /s"
        else
          ls -R tests
        fi
    
    - name: Run tests
      run: poetry run pytest tests -s -x --cov=bitser -vv
      
    - name: Upload coverage
      uses: codecov/codecov-action@v4
